name: Simple Network Tests

on:
  release:
    types: [created] # Triggers when a new GitHub release is created
  workflow_dispatch: # Allows manual triggering

jobs:
  build-windows:
    name: Build for Windows x64
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        # *** IMPORTANT: Update this version if you switch SDKs (e.g., to '8.0.x') ***
        dotnet-version: '9.0.x' # Using .NET 9 SDK based on current setup

    - name: Install MAUI Windows Workload ONLY
      # Install only the necessary windows workload to potentially speed up setup
      run: dotnet workload install maui-windows --ignore-failed-sources

    - name: Restore Dependencies
      run: dotnet restore ./NetworkTroubleshooter/NetworkTroubleshooter.csproj

    - name: Publish for Windows x64
      # *** IMPORTANT: Verify the TargetFramework in NetworkTroubleshooter.csproj and update '-f' if needed ***
      run: |
        $targetFramework = (Select-String -Path .\NetworkTroubleshooter\NetworkTroubleshooter.csproj -Pattern '<TargetFrameworks>.*net[\d\.]+-windows[\d\.\-]+.*</TargetFrameworks>' | Select-Object -First 1).Line -replace '<TargetFrameworks>.*(net[\d\.]+-windows[\d\.\-]+).*</TargetFrameworks>', '$1' -replace ';.*',''
        Write-Host "Detected Windows TargetFramework: $targetFramework"
        if (-not $targetFramework) { throw "Could not detect Windows TargetFramework in csproj" }
        dotnet publish .\NetworkTroubleshooter\NetworkTroubleshooter.csproj -f $targetFramework -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x64/
      shell: pwsh

    - name: Archive Windows Artifact
      run: Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./NetworkTroubleshooter-win-x64.zip
      shell: pwsh 

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetworkTroubleshooter-win-x64
        path: ./NetworkTroubleshooter-win-x64.zip

  release:
    name: Create GitHub Release Assets
    needs: [build-windows] # Only depends on the windows build now
    runs-on: ubuntu-latest

    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: NetworkTroubleshooter-win-x64
        path: ./artifacts/win-x64

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./artifacts/win-x64/NetworkTroubleshooter-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 